config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "static_pages#home"

  post "/payment",  to: "static_pages#create"

  get '/payment_status', to: 'static_pages#payment_status'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
  require 'fedapay'

  def create

    begin
      # Configuration de l'API FedaPay
      FedaPay.api_key = 'sk_sandbox_XXXXXXXXXXXXX'
      FedaPay.environment = 'env' # 'sandbox' ou 'live' en production
  
      # Création de la transaction
      transaction = FedaPay::Transaction.create(
        amount: 100000,
        currency: { iso: 'XOF' },
        callback_url: "http://localhost:3000/payment_status",
        description: 'Achat de montre de luxe',
      )
  
      # Génération du token de la transaction
      token = transaction.generate_token
  
      # Redirection automatique vers la page de paiement
      redirect_to token.url, allow_other_host: true
  
      puts "Transaction successfully created : #{transaction.inspect}"
  
    rescue FedaPay::Error => e
      # Capture des erreurs spécifiques à FedaPay
      puts "FedaPay Error: #{e.message}"
      render json: { error: "Une erreur est survenue lors de la création de la transaction : #{e.message}" }, status: :unprocessable_entity
  
    rescue StandardError => e
      # Capture des erreurs générales
      puts "Standard Error: #{e.message}"
      render json: { error: "Une erreur inattendue est survenue. Veuillez réessayer plus tard." }, status: :internal_server_error
    end
  end
  

#Gestion des calbacks et statuts de la transaction
    def payment_status

      transaction_id = params[:id]
      
      if transaction_id.blank?
        flash[:alert] = "ID de transaction non fourni."
        redirect_to root_path and return
      end
    
      begin
        transaction = FedaPay::Transaction.retrieve(transaction_id)
        status = transaction.status
    
        flash[:notice] = if %w[approved transferred].include?(status)
                            "Paiement réussi !"
                          else
                            "Échec du paiement. Statut : #{status}"
                          end
      rescue StandardError => e
        flash[:alert] = "Erreur lors du traitement du paiement : #{e.message}"
      end
    
      redirect_to root_path
    end
    
  end
  

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Dosbyl App"
        if page_title.empty?
          base_title
        else
          page_title + " | " + base_title
        end
      end 
      
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer starts here -->
<footer class="page-footer font-small mdb-color pt-4">
    <!-- Footer Links -->
    <div class="container text-center text-md-left">
        <!-- Grid row -->
        <div class="row d-flex align-items-center">

            <!-- Grid column -->
            <div class="col-12">

                <!--Copyright-->
                <p class="text-center text-md-center">© 2025 Copyright:
                    <a href="https://www.fedapay.com/">
                        <strong> FedaPay</strong>
                    </a>
                </p>
            </div>
        </div>
        <!-- Grid row -->
    </div>
    <!-- Footer Links -->
</footer>
<!-- Footer -->
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>

app/views/layouts/_header.html.erb
    <div class="container"> 
        
        <div class="div">
            <h1 class="h1 mt-4 mb-3" style="text-align:center; margin-top:25px; margin-bottom:25px"><strong>Nos Produits</strong></h1>
        </div>


    </div>

    <div class="container mt-5">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
     <%= render 'layouts/header' %>

     <% flash.each do |key, message| %>
        <div id="flash-message" class="alert alert-<%= key %>">
          <%= message %>
        </div>
      <% end %>

      <%= yield %>

      </div>

      <script>
      document.addEventListener("DOMContentLoaded", function() {
        var flashMessage = document.getElementById("flash-message");
        if (flashMessage) {
          alert(flashMessage.textContent);
        }
      });
    </script>
      
      <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/static_pages/home.html.erb
        <style>

        .card {
            transition: transform 0.2s;
        }

        .card:hover {
            transform: scale(1.05);
        }
        /* Style du message flash */
    .flash-message {
        position: fixed;
        top: 20px;
        right: 20px;
        background-color: #28a745; /* Vert pour succès */
        color: white;
        padding: 15px;
        border-radius: 5px;
        display: none;
        z-index: 1000;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }
    .flash-message.error {
        background-color: #dc3545; /* Rouge pour échec */
    }
    </style>

    
        
        <div class="row">

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-5 shadow-sm">
                    <%= image_tag '1.webp', class: 'img-fluid' %>

                    <div class="card-body">
                        <div class="card-title">
                            <h2>Citizen </h2>
                        </div>
                        <div class="card-text">
                            <p>
                            Montre Citizen - Collection Super Titanium - Mechanical - 
                            Deux aiguilles, date, composée d'un boîtier titane de 40,5 mm,
                            d'un cadran vert avec petite seconde et d'un bracelet titane.
                            </p>
                        </div>
                          <%= button_to 'Payer 100000 FCFA', payment_path, method: :post, data: { turbo: false }, class: "btn btn-outline-primary rounded-1 float-end" %>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-5 shadow-sm">
                    <%= image_tag '2.webp', class: 'img-fluid' %>

                    <div class="card-body">
                        <div class="card-title">
                            <h2>Frédérique Constant </h2>
                        </div>
                        <div class="card-text">
                            <p>
                            Montre Frédérique Constant Classics Index, automatique 3
                            aiguilles, composée d'un boitier acier de 40 mm, d'un cadran
                            argenté coeur ouvert avec les clous de Paris guilloché sur bracelet en cuir noir.
                            </p>
                        </div>
                         <%= button_to 'Payer 100000 FCFA', payment_path, method: :post, data: { turbo: false }, class: "btn btn-outline-primary rounded-1 float-end" %>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-5 shadow-sm">
                    <%= image_tag '3.webp', class: 'img-fluid' %>

                    <div class="card-body">
                        <div class="card-title">
                            <h2>Zeppelin</h2>
                        </div>
                        <div class="card-text">
                            <p>
                            Cette montre Zeppelin de la collection 100 ans se compose
                            d'un boitier rond de 42mm en acier, d'un cadran de couleur
                            ivoire et d'un bracelet en cuir noir. Etanchéité 50m.
                            </p>
                        </div>
                         <%= button_to 'Payer 100000 FCFA', payment_path, method: :post, data: { turbo: false }, class: "btn btn-outline-primary rounded-1 float-end" %>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-5 shadow-sm">
                    <%= image_tag '4.webp', class: 'img-fluid' %>

                    <div class="card-body">
                        <div class="card-title">
                            <h2>Maserati</h2>
                        </div>
                        <div class="card-text">
                            <p>
                            Montre de la collection Competizione, 3 aiguilles date,
                            composée d'un boitier de 43mm en acier, d'un cadran bleu
                            et d'un bracelet en acier.
                            </p>
                        </div>
                          <%= button_to 'Payer 100000 FCFA', payment_path, method: :post, data: { turbo: false }, class: "btn btn-outline-primary rounded-1 float-end" %>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-5 shadow-sm">
                    <%= image_tag '5.webp', class: 'img-fluid' %>

                    <div class="card-body">
                        <div class="card-title">
                            <h2>Tissot </h2>
                        </div>
                        <div class="card-text">
                            <p>
                            Montre de la collection PR100,
                            mouvement quartz chronographe, boitier en acier argenté
                            de 40mm avec un cadran vert sur un bracelet en acier argenté.
                            </p>
                        </div>
                        <%= button_to 'Payer 100000 FCFA', payment_path, method: :post, data: { turbo: false }, class: "btn btn-outline-primary rounded-1 float-end" %>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-5 shadow-sm">
                    <%= image_tag '6.webp', class: 'img-fluid' %>

                    <div class="card-body">
                        <div class="card-title">
                            <h2>Seiko </h2>
                        </div>
                        <div class="card-text">
                            <p>
                            Montre Seiko Presage Cocktail Edition homme automatique,
                            boitier rond de 40,5mm, 3 aiguilles date, cadran bleu clair avec index,
                            bracelet en acier.
                            </p>
                        </div>
                   <%= button_to 'Payer 100000 FCFA', payment_path, method: :post, data: { turbo: false }, class: "btn btn-outline-primary rounded-1 float-end" %>
                    </div>
                </div>
            </div>
            <!--Row-->
        </div>